#!/usr/bin/env bash
LOG="${HOME}/dotfiles.log"
GITHUB_USER="timothysparg"
GITHUB_REPO="df"

_process() {
    echo "$(date) PROCESSING:  $@" >> $LOG
    printf "$(tput setaf 6) %s...$(tput sgr0)\n" "$@"
}

_success() {
  local message=$1
  printf "%s✓ Success:%s\n" "$(tput setaf 2)" "$(tput sgr0) $message"
}

link_dotfiles() {
    # symlink files to the HOME directory.
    if [[ -f "opt/files" ]]; then
        _process "→ Symlinking dotfiles in /configs"

        # Set variable for list of files
        files="opt/files"

        # Store IFS separator within a temp variable
        OIFS=$IFS
        # Set the separator to a carriage return & a new line break
        # read in passed-in file and store as an array
        IFS=$'\r\n'
        links=($(cat "${files}"))

        # Loop through array of files
        for index in ${!links[*]}
        do
            for link in ${links[$index]}
            do
                _process "→ Linking ${links[$index]}"
                # set IFS back to space to split string on
                IFS=$' '
                # create an array of line items
                file=(${links[$index]})
                # Create symbolic link
                echo "current: $PWD/${file[0]}"
                 echo "link: ${HOME}/${file[1]}"

                ln -fs "$PWD/${file[0]}" "${HOME}/${file[1]}"
            done
            # set separater back to carriage return & new line break
            IFS=$'\r\n'
        done

        # Reset IFS back
        IFS=$OIFS

        source "${HOME}/.bash_profile"
        [[ $? ]] && _success "All files have been copied"
    fi
}

apt() {
  _process "→ Updating apt packages"
  apt-get update
  _process "→ Installing apt packages"
  xargs apt-get install -y <opt/apt-packages

  [[ $? ]] && _success "All apt packages installed and updated"
}

custom_installs(){
  _process "→ Calling custom install scripts"
  for install_script in opt/custom/*
  do
    _process "→ Calling $install_script"
    ./$install_script
  done
  [[ $? ]] && _success "All custom install scripts installed"
}


install() {
  link_dotfiles
  apt
  custom_installs
}

install

# after installation is complete, start tmux
tmux